# Generated by Django 3.2 on 2022-01-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220127_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='order_number',
        ),
    ]
